name: Report BUG
description: Please look at the  issues list first to confirm similar issues weren't created
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which OS do you use?
      options:
        - Linux
        - MacOS
        - Windows
        - Other
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python
      description: Which python do you use?
  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Please tell us what's happen
    validations:
      required: true
