name: install
on:
  push:
  pull_request:
    types: [opened, synchronize]
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    name: use python${{matrix.python-version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: install
        run: |
          pip install -U pip
          python3 install.py --action --gen-script